import pandas as pd

def default_persona_journeys() -> pd.DataFrame:
    return pd.DataFrame([
        {"persona":"Premium Power Shopper","preferred_channels":"app_push > email","cadence_guidance":"2–3 touches/week; avoid heavy discounting","core_motivation":"Exclusive access + premium results","primary_barrier":"Too much generic promo; expects personalization","awareness":"Influencer drops, new launches, premium routine content","consideration":"Ingredient education + comparison guides + UGC","conversion":"Early access, limited-time bundles, tier perks","retention":"Replenishment reminders + concierge-style recommendations","advocacy":"VIP referral offers + review prompts on hero products"},
        {"persona":"Deal Hunter","preferred_channels":"email > sms","cadence_guidance":"1–2 touches/week; highlight price transparency","core_motivation":"Savings + value bundles","primary_barrier":"Will churn if promos stop","awareness":"Sale teasers, value edits, under-$25 picks","consideration":"Price drop alerts, bundle comparisons","conversion":"Limited-time coupons, cart recovery with incentive","retention":"Monthly deal calendar + personalized promo categories","advocacy":"Share-a-deal prompts + rewards points education"},
        {"persona":"Ingredient-Conscious","preferred_channels":"email > app_push","cadence_guidance":"1–2 touches/week; focus on trust + proof","core_motivation":"Clean/vegan/cruelty-free alignment","primary_barrier":"Skepticism; needs transparency","awareness":"Label-focused collections + education content","consideration":"Certifications, ingredient explainers, dermatologist notes","conversion":"Trial sizes, routines, satisfaction guarantees","retention":"Routine builders + restock reminders","advocacy":"Community spotlight + review prompts for clean picks"},
        {"persona":"Brand Loyalist","preferred_channels":"email > app_push","cadence_guidance":"1–2 touches/week; personalize by brand","core_motivation":"Preferred brand trust + consistency","primary_barrier":"May ignore non-brand messages","awareness":"Brand news, launches, creator content","consideration":"How-to use, routine pairings within brand","conversion":"Brand bundle offers, early access","retention":"Replenishment, subscribe & save, tier perks","advocacy":"Brand community, loyalty milestones"},
        {"persona":"Category Explorer","preferred_channels":"app_push > email","cadence_guidance":"2 touches/week; keep novelty high","core_motivation":"Discovery + experimenting","primary_barrier":"Decision paralysis","awareness":"New arrivals, trending edits, quizzes","consideration":"Guided discovery, compare charts, UGC snippets","conversion":"Curated bundles, ‘complete the look’ suggestions","retention":"Personalized discovery feed + seasonal picks","advocacy":"Share-your-routine + review prompts"},
        {"persona":"Reviewer / Researcher","preferred_channels":"email > app_push","cadence_guidance":"1–2 touches/week; prioritize proof + detail","core_motivation":"Informed decisions","primary_barrier":"Needs evidence; distrusts hype","awareness":"Top-rated lists, ‘tested’ content","consideration":"Ingredient/claims breakdown, long-form guides","conversion":"Free returns, samples, social proof","retention":"Replenishment + personalized review requests","advocacy":"Top reviewer perks + community badges"},
        {"persona":"Routine Replenisher","preferred_channels":"email > sms","cadence_guidance":"1–2 touches/week; keep messages utility-first","core_motivation":"Consistency + convenience","primary_barrier":"Forgets; doesn’t browse","awareness":"Routine reminders + essentials","consideration":"Reorder suggestions + ‘buy again’","conversion":"1-click reorder + loyalty points","retention":"Smart restock schedule + replenishment bundles","advocacy":"Referral nudges after repeat purchase"},
        {"persona":"Casual Browser","preferred_channels":"email","cadence_guidance":"1 touch/week; test content hooks","core_motivation":"Light inspiration","primary_barrier":"Low intent","awareness":"Seasonal edits + quick picks","consideration":"Short quizzes + curated sets","conversion":"Gentle cart recovery + low-friction offers","retention":"Occasional highlights + wishlist reminders","advocacy":"Soft review asks after first purchase"},
        {"persona":"Lapsed / Winback","preferred_channels":"email > sms","cadence_guidance":"2-touch winback sequence; then pause if no response","core_motivation":"Return to value","primary_barrier":"Disengaged; fatigue risk","awareness":"‘We miss you’ + newness + value hook","consideration":"Personalized picks based on history","conversion":"Winback incentive + urgency","retention":"Re-activate with restock + preference capture","advocacy":"Referral once reactivated"}
    ])
